"""
Workflow 3: Send SOW and Archive
Triggered when SOW is approved, sends to client and archives files
"""

from app.services import (
    GoogleDriveService,
    GoogleSheetsService,
    GoogleDocsService,
    GmailService,
    RedisService
)
from app.config import Config
import logging

logger = logging.getLogger(__name__)


async def send_sow_and_archive(
    engagement_id: str,
    config: Config
) -> None:
    """
    Send SOW to client and archive files

    Steps:
    1. Get engagement data from Redis
    2. Export SOW as PDF
    3. Send SOW to client via email
    4. Move transcript to archive folder
    5. Update Tracker status to 'completed'
    6. Delete Redis state
    7. Create client folder (optional organization)

    Args:
        engagement_id: Engagement ID
        config: Application configuration
    """
    try:
        logger.info(f"Starting send & archive for engagement: {engagement_id}")

        # Initialize services
        drive = GoogleDriveService(config.google_credentials_path)
        sheets = GoogleSheetsService(config.google_credentials_path)
        docs = GoogleDocsService(config.google_credentials_path)
        gmail = GmailService(
            config.google_credentials_path,
            config.gmail_send_as,
            use_oauth2=config.gmail_use_oauth2,
            oauth2_refresh_token=config.gmail_refresh_token,
            oauth2_client_id=config.gmail_client_id,
            oauth2_client_secret=config.gmail_client_secret
        )
        redis = RedisService(config.upstash_redis_rest_url, config.upstash_redis_rest_token)

        # Step 1: Get engagement data
        logger.info("Step 1: Getting engagement data from Redis")
        state_data = redis.get_state(engagement_id)

        if not state_data:
            raise ValueError(f"No state data found for engagement {engagement_id}")

        sow_doc_id = state_data['data']['sow_doc_id']
        client_company = state_data['data']['client']
        decision_maker_email = state_data['data']['decision_maker_email']
        transcript_file_id = state_data['data'].get('file_id')

        # Step 2: Export SOW as PDF
        logger.info("Step 2: Exporting SOW as PDF")
        sow_pdf = docs.export_as_pdf(sow_doc_id)

        # Step 3: Send SOW to client
        logger.info("Step 3: Sending SOW to client")
        email_body = f"""Dear {decision_maker_email.split('@')[0].title()},

Thank you for your interest in AIIR Consulting's executive coaching services.

Please find attached the Statement of Work for the coaching engagement we discussed.

We look forward to partnering with you on this important development initiative.

Best regards,
AIIR Consulting Team

---
This SOW was generated by the AIIR Automation System.
"""

        gmail.send_email_with_attachment(
            to=decision_maker_email,
            subject=f"Statement of Work - {client_company}",
            body=email_body,
            attachment_filename=f"SOW_{client_company}.pdf",
            attachment_content=sow_pdf,
            is_html=False
        )

        # Step 4: Move transcript to archive
        if transcript_file_id:
            logger.info("Step 4: Moving transcript to archive folder")
            drive.move_file(transcript_file_id, config.archive_folder_id)

        # Step 5: Update Tracker status
        logger.info("Step 5: Updating Tracker status to completed")
        sheets.update_row_by_engagement_id(
            config.tracker_sheet_id,
            config.tracker_tab_name,
            engagement_id,
            {
                'Q': 'completed',  # Column Q: Status
            }
        )

        # Step 6: Delete Redis state
        logger.info("Step 6: Cleaning up Redis state")
        redis.delete_state(engagement_id)

        # Optional Step 7: Create client folder
        logger.info("Step 7: Organizing files in client master folder")
        try:
            # Create a folder for this client if it doesn't exist
            client_folder_name = f"{client_company}_{engagement_id}"
            client_folder_id = drive.create_folder(
                client_folder_name,
                config.client_master_folder_id
            )

            # Move SOW to client folder
            drive.move_file(sow_doc_id, client_folder_id)

            logger.info(f"Created and organized client folder: {client_folder_name}")
        except Exception as e:
            logger.warning(f"Could not create client folder (non-critical): {e}")

        logger.info(f"Workflow completed successfully for engagement {engagement_id}")

    except Exception as e:
        logger.error(f"Error in workflow 3: {e}")
        raise
